nelmio_api_doc:
    documentation:
        info:
            title: Civilipédia API
            description: API REST du wiki collaboratif Civilipédia
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)