security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 13

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/auth/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

    access_control:
    - { path: ^/api/doc, roles: PUBLIC_ACCESS }
    - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
    - { path: ^/api/contact, roles: PUBLIC_ACCESS }
    - { path: ^/api/articles, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }